name: Build iOS release package

run-name: Build iOS release package (${{ inputs.environment }} ${{ inputs.build_number}})

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment to build package for'
        required: true
      build_number:
        type: string
        required: true

permissions:
  contents: read

env:
  BUILD_NUM: ${{ inputs.build_number }}
  PROJPATH: "visitz/Visitz"
  DOTNET_SDK_VERSION: "10.0.102"
  GLOBAL_JSON_PATH: "global.json"
  XCODE_VERSION: "26.2"

jobs:

  build-ios-package:
    name: Building, archiving and uploading IPA to GitHub
    runs-on: macOS-15
    environment: ${{ inputs.environment }}
    timeout-minutes: 200
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get build version
        run: |
          OUTPUT_VERSION=$(xmllint --xpath 'string(/Project/PropertyGroup/VisitzVersion)' ${{ env.PROJPATH }}/Visitz.props)
          echo "OUTPUT_VERSION=$OUTPUT_VERSION" >> "$GITHUB_ENV"

      - name: Set build name
        run: |
          # TODO: read "MCFD Mobility" app name from MSBuild instead

          OUTPUT_NAME="MCFD Mobility-iOS-${{ vars.ENV_LABEL }}-$OUTPUT_VERSION.$BUILD_NUM"
          echo "OUTPUT_NAME=$OUTPUT_NAME" >> "$GITHUB_ENV"

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Import code-signing certificates
        uses: Apple-Actions/import-codesign-certs@b610f78488812c1e56b20e6df63ec42d833f2d14 # v6.1.0
        with: 
          p12-file-base64: ${{ secrets.APPLE_ENTERPRISE_BUILD_CERTIFICATE_BASE_64 }}
          p12-password: ${{ secrets.APPLE_ENTERPRISE_BUILD_CERTIFICATE_PASSWORD }}

      - name: Retrieve certificate name
        env:
          APPLE_ENTERPRISE_BUILD_CERTIFICATE_BASE_64: ${{ secrets.APPLE_ENTERPRISE_BUILD_CERTIFICATE_BASE_64 }}
          TEMP_CERT_PATH: "temp-cert.p12"
        run: |
          echo -n "$APPLE_ENTERPRISE_BUILD_CERTIFICATE_BASE_64" | base64 --decode -o $TEMP_CERT_PATH

          SUBJECT=$(openssl pkcs12 -in "$TEMP_CERT_PATH" \
            -password pass:"${{ secrets.APPLE_ENTERPRISE_BUILD_CERTIFICATE_PASSWORD }}" \
            -nodes -nokeys \
            | openssl x509 -noout -subject)

          COMMON_NAME=$(./.github/scripts/get_common_name.sh "$SUBJECT")
          echo "IOS_BUILD_CERTIFICATE_NAME=$COMMON_NAME" >> "$GITHUB_ENV"

          rm $TEMP_CERT_PATH

      - name: Install provisioning profile and retrieve name
        env:
          IOS_BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_BUILD_PROVISION_PROFILE_BASE64 }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

          echo -n "$IOS_BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # Apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

          # Retrieve profile name
          echo "IOS_CODE_SIGN_PROVISION_PROFILE_NAME=$(/usr/libexec/PlistBuddy \
            -c 'Print Name' /dev/stdin \
            <<< $(security cms -D -i $PP_PATH))" >> "$GITHUB_ENV"

      - name: Inflate ${{ env.GLOBAL_JSON_PATH }}
        run: |
          cp ${{ env.GLOBAL_JSON_PATH }}.template ${{ env.GLOBAL_JSON_PATH }}

      - name: Force .NET SDK version ${{ env.DOTNET_SDK_VERSION }}
        uses: jossef/action-set-json-field@890d7642122dbb2833dddd2003659bb71a2b21fe # v2.2
        with:
          file: ${{ env.GLOBAL_JSON_PATH }}
          field: sdk.version
          value: ${{ env.DOTNET_SDK_VERSION }}

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@1641575d87647fb969c0545f0b6a76873e328b7c # v5.0.0
        with:
          disable-job-summary: true
        env:
          JF_PROJECT: ${{ secrets.ARTIFACTORY_PROJECT }}
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_USER: ${{ secrets.ARTIFACTORY_SERVICE_ACCOUNT_USER }}
          JF_PASSWORD: ${{ secrets.ARTIFACTORY_SERVICE_ACCOUNT_PWD }}

      - name: Setup .NET SDK and workloads
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # 5.2.0
        with:
          cache-dependency-path: ${{ env.PROJPATH }}/packages.lock.json
          cache: true
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}

      - name: Install .NET MAUI ${{ env.MAUI_WORKLOAD_VERSION }} workloads
        run: |
          dotnet --version
          dotnet workload install maui maui-ios --version ${{ env.DOTNET_SDK_VERSION }}

      - name: .NET release build for iOS (${{ inputs.environment }})
        run: |
          dotnet --version
          dotnet publish $PROJPATH \
            --framework net10.0-ios \
            --configuration Release \
            -p:ApplicationVersion=${{ env.BUILD_NUM }} \
            -p:DeploymentEnvironment=${{ vars.ENV_NAME }} \
            -p:BuildTypeColor=${{ vars.BUILD_TYPE_COLOR }} \
            -p:CodesignKey="${{ env.IOS_BUILD_CERTIFICATE_NAME }}" \
            -p:CodesignProvision="${{ env.IOS_CODE_SIGN_PROVISION_PROFILE_NAME }}" \
            -p:UseAppSettings=true \
            -p:Oidc_AuthenticationDomain="${{ vars.AUTHENTICATION_DOMAIN }}" \
            -p:Oidc_ClientId="${{ vars.KEYCLOAK_CLIENT_ID }}" \
            -p:Oidc_RedirectUri="${{ vars.REDIRECT_URI }}" \
            -p:Api_HttpsApiDomain="${{ vars.API_BASE_URL }}" \
            -p:ContactInfo_MailToAuthorize="${{ secrets.MAILTO_AUTHORIZE }}" \
            -p:ContactInfo_AccessRequestFormUrl="${{ vars.ACCESS_REQUEST_FORM_URL }}" \
            -p:ContactInfo_FeedbackSurveyUrl="${{ vars.FEEDBACK_SURVEY_URL }}" \
            -p:Debug_EnableDebugOptions=${{ vars.DEBUG_OPTIONS }}

      - name: Prepare output package
        run: |
          cd ${{ env.PROJPATH }}/bin/Release/net10.0-ios/ios-arm64/publish
          mv "MCFD Mobility.ipa" "$OUTPUT_NAME.ipa"

      - name: Push build to Artifactory
        env:
          # TODO: make URL for job run (https://stackoverflow.com/a/70566764)
          ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          jf rt upload \
            "${{ env.PROJPATH }}/bin/Release/net10.0-ios/ios-arm64/publish/$OUTPUT_NAME.ipa" \
            "${{ secrets.ARTIFACTORY_REPO_NAME }}/${{ vars.ENV_LABEL }}-iOS/$OUTPUT_NAME.ipa" \
            --build-name="$OUTPUT_NAME" \
            --build-number="$OUTPUT_VERSION.$BUILD_NUM" \
            --target-props="version=$OUTPUT_VERSION;commit=${{ github.sha }};action_url=$ACTION_URL"
