name: Run .NET MAUI tests

run-name: Run .NET MAUI tests (${{ github.ref_name }})

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - visitz/**/*

permissions:
  contents: read
  actions: read
  checks: write

env:
  BASE_PROJPATH: "./visitz"
  DOTNET_SDK_VERSION: "10.0.102"
  GLOBAL_JSON_PATH: "global.json"

jobs:
  run-maui-tests:
    name: Build and test .NET MAUI project
    runs-on: windows-2022
    timeout-minutes: 40
    env:
      TEST_RESULTS: "testResults"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Inflate ${{ env.GLOBAL_JSON_PATH }}
        run: |
          Copy-Item .\${{ env.GLOBAL_JSON_PATH }}.template .\${{ env.GLOBAL_JSON_PATH }}

      - name: Force .NET SDK version ${{ env.DOTNET_SDK_VERSION }}
        uses: jossef/action-set-json-field@890d7642122dbb2833dddd2003659bb71a2b21fe # v2.2
        with:
          file: ${{ env.GLOBAL_JSON_PATH }}
          field: sdk.version
          value: ${{ env.DOTNET_SDK_VERSION }}

      - name: Setup .NET SDK and workloads
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # 5.2.0
        with:
          cache-dependency-path: ${{ env.BASE_PROJPATH }}\Visitz\packages.lock.json
          cache: true
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}

      - name: Install .NET MAUI workload
        working-directory: ${{ env.BASE_PROJPATH }}
        run: |
          dotnet --version
          dotnet workload install maui ios maccatalyst maui-ios maui-windows maui-maccatalyst --version ${{ env.DOTNET_SDK_VERSION }}

      - name: Build solution
        working-directory: ${{ env.BASE_PROJPATH }}
        run: |
          dotnet --version
          dotnet build --framework net10.0

      # Running with --no-build to work around an MSBuild targets issue.
      # (Details: build throws an error about a missing "Visitz.appSettings.json" file. That file should only exist
      # when running a build in Release mode.)
      - name: Run tests
        working-directory: ${{ env.BASE_PROJPATH }}
        run: |
          dotnet --version
          dotnet test `
            --framework net10.0 `
            --logger "trx;LogFilePrefix=${{ env.TEST_RESULTS }}" `
            --no-build

      - name: Report tests
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        if: success() || failure()
        with:
          name: Visitz MAUI Tests
          path: "**/${{ env.TEST_RESULTS }}*.trx"
          reporter: dotnet-trx
